### ISSUE TITLE
selenium-side-runner arguments `--config` and `--configuration-file` do not work

### ISSUE THREAD

**Issue by serpi90** [SeleniumHQ/selenium-ide#666]
## 🐛 Bug Report

selenium-side-runner arguments `--config` and `--configuration-file` do not work, only `--config-file` is working.

## To Reproduce

run any test suite with `--config <filepath>` or `--configuration-file <filepath>`  and `--debug`

you should see:
> debug:   Could not load /tmp/runner/.side.yml

## Expected behavior

Either:
- the configuration file should be loaded with any of the 3 options
- remove --config and --configuration-file and keep the working one as it is misleading.

## Project file reproducing this issue (highly encouraged)

N/A

## Environment

Docker under linux
```Dockerfile
FROM node:10-alpine
RUN npm install --global selenium-side-runner
```

**Comment by corevo** [comment]
We will have a fix soon, it will remove `--configuration-file`, it will fix `--config`.

**Comment by bethy0100** [comment]
Hi, for me it didn't work with --config-file, run test suite with --config-file, --config <filepath> or --configuration-file <filepath> and --debug
you should see:
debug: Could not load /root/.side.yml

**Comment by bethy0100** [comment]
For more information I am using the example: https://github.com/nixel2007/docker-selenium-side-runner and I try to run from a git lab docker, to complete the cycle of ci

**Comment by corevo** [comment]
@bethy0100 how do you pass the `--config-file` to `selenium-side-runner`?

**Comment by bethy0100** [comment]
yes, I tried with
selenium-side-runner -s http: // chromedriver: 4444 --output-directory / root / out /sides/*.side
or 
selenium-side-runner --config-file "root/.side.yml", 
the result is the same:
debug: Could not load /root/.side.yml


thanks for you help

**Comment by corevo** [comment]
From what you are saying it did try to find the file you specified, but it wasn't there, did you copy it into the image?

**Comment by bethy0100** [comment]
yes of course, the file is copied

**Comment by bethy0100** [comment]
This is another way to pass --config-file:

selenium-side-runner --debug --config-file "/builds/QA/pruebasautomatizadas/gestion-flujos/config.yaml" --output-directory ../out /sides/*.side

The result:

selenium-side-runner_1  | inicio -ejecucioooon
 selenium-side-runner_1  | debug:   Could not load /builds/QA/pruebasautomatizadas/gestion-flujos/config.yaml
 selenium-side-runner_1  | debug:   {
 selenium-side-runner_1  |   capabilities: { browserName: 'chrome' },

**Comment by bethy0100** [comment]
if you need more information.
This is my .gitlab-ci.yml from gilab:

```yaml
image: 
    name: docker/compose:1.24.1 
    entrypoint: [""]
    
 
services:
  - docker:dind


stages:
 - selenium

variables:
 PROYECTO : "/root/selenium/proyecto"
 DOCKER_HOST: "tcp://72.80.6.44:2375"

gestion-flujos:
 stage: selenium
 
 script:
  - export PROYECTO=$PROYECTO
  - export PATH=$PATH:$PROYECTO
  - export DOCKER_HOST=$DOCKER_HOST
  - echo $DOCKER_HOST
  - echo $PATH
  - docker-compose build
  - docker-compose up
  - docker-compose down
 

 only:
  - master
  
 when: manual
 
 tags:
  - deploy
```
